# Generated by Django 6.0.7 on 2026-07-13 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip', 'IP address'), ('url', 'URL')], max_length=16)),
                ('value', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='False once a scan stops confirming this asset still resolves/responds.')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='assets.asset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'asset_type'], name='assets_asse_organiz_2c4606_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'value'), name='unique_asset_per_org'),
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.UniqueConstraint(fields=('asset', 'name', 'version'), name='unique_technology_per_asset'),
        ),
    ]
