# Generated by Django 6.0.7 on 2026-07-13 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('open_port', 'Open port'), ('missing_header', 'Missing security header'), ('expired_ssl', 'Expired/expiring SSL certificate'), ('exposed_service', 'Exposed service'), ('nuclei_match', 'Nuclei match'), ('subdomain_discovered', 'New subdomain discovered'), ('dns_change', 'DNS record change')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='assets.asset')),
                ('scan_job', models.ForeignKey(help_text='The scan run that most recently confirmed this finding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scanning.scanjob')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['asset', 'is_active'], name='findings_fi_asset_i_6da4ae_idx'), models.Index(fields=['finding_type', 'severity'], name='findings_fi_finding_9f49c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'dedupe_key'), name='unique_finding_per_asset')],
            },
        ),
    ]
