# Generated by Django 6.0.7 on 2026-07-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='finding_type',
            field=models.CharField(choices=[('open_port', 'Open port'), ('missing_header', 'Missing security header'), ('expired_ssl', 'Expired/expiring SSL certificate'), ('exposed_service', 'Exposed service'), ('nuclei_match', 'Nuclei match'), ('subdomain_discovered', 'New subdomain discovered'), ('dns_change', 'DNS record change'), ('screenshot', 'Website screenshot')], max_length=32),
        ),
    ]
