# Generated by Django 6.0.7 on 2026-07-13 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Null for org-level scans (e.g. subdomain discovery).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'scanner_name', 'status'], name='scanning_sc_organiz_f42f2d_idx')],
            },
        ),
    ]
