# Generated by Django 6.0.7 on 2026-07-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0003_alter_scanjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
